service: product-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  environment:
    PGUSER: ${env:PGUSER}
    PGHOST: ${env:PGHOST}
    PGPASSWORD: ${env:PGPASSWORD}
    PGDATABASE: ${env:PGDATABASE}
    PGPORT: ${env:PGPORT}
    CatalogItemsQueue:
      Ref: CatalogItemsQueue
    SNS_ARN:
      Ref: SNSTopic
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "sns:*"
          Resource: 
            Ref: SNSTopic
resources:
  Resources:
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalog-items-queue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: catalog-items-created-topic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: dogali.elif@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  getProductList:
    handler: handler.getProducts
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsListById:
    handler: handler.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: /products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn
custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
